<?php

namespace Acme\GuildBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuildMembresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuildMembresRepository extends EntityRepository
{
}
