<?php

namespace Acme\GuildBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaningRepository extends EntityRepository
{
}
